version: 2.1
jobs:
  # unit_test:
  #   docker:
  #     - image: circleci/node:10.16.3
  #   steps:
  #     - checkout
  #     - node/with-cache:
  #       - run: yarn install
  #     - run: yarn unit
    build_docker:
        working_directory: ~/repo
        docker:
            - image: circleci/node:12.10
        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "yarn.lock" }}
            - run:
                name: Install packages weee
                command: yarn install
            - save_cache:
                key: dependency-cache-{{ checksum "yarn.lock" }}
                paths:
                    - ./node_modules
            - run:
                name: Install Docker Compose
                command: |
                    set -x
                    sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                    sudo chmod +x /usr/local/bin/docker-compose
            - setup_remote_docker
            - run:
                name: Run docker compose
                command: sudo docker-compose up
                background: true
workflows:
    deploy:
      jobs:
        # - unit_test
        - build_docker