version: 2.1
jobs:
    install:
        working_directory: ~/repo
        docker:
            - image: circleci/node:12.10
        steps:
            - checkout
            - restore_cache:
                keys: 
                    - dependency-cache-{{ checksum "package.json" }}
                    - dependency-cache-{{ checksum "yarn.lock" }}
                    - dependency-cache
            - run:
                name: Install packages weee
                command: yarn install
            - save_cache:
                key: dependency-cache
                paths:
                    - ./node_modules
            - run:
                name: Install Docker Compose
                command: |
                    set -x
                    sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                    sudo chmod +x /usr/local/bin/docker-compose
    unit_test:
        working_directory: ~/repo
        docker:
            - image: circleci/node:12.10
        steps:
            - checkout
            - restore_cache:
                keys: 
                    - dependency-cache-{{ checksum "package.json" }}
                    - dependency-cache-{{ checksum "yarn.lock" }}
                    - dependency-cache
            - run: 
                name: Launch unit test
                command: yarn unit
    launch_docker_compose:
        working_directory: ~/repo
        docker:
            - image: circleci/node:12.10
        steps:
            - checkout
            - restore_cache:
                keys: 
                    - dependency-cache-{{ checksum "package.json" }}
                    - dependency-cache-{{ checksum "yarn.lock" }}
                    - dependency-cache
            - setup_remote_docker
            - run:
                name: Run docker compose
                command: docker-compose up -d
            - run: 
                name: View docker containers
                command: docker ps
            - run:
                name: Migration
                command: docker exec repo_server_1 node migration.js up
            # - run: 
            #     name: Launch functional tests
            #     command: docker exec repo_server_1 
workflows:
    hjshdjkgvdf:
        jobs:
            - install
            - unit_test:
                requires: 
                    - install
            - launch_docker_compose: 
                requires: 
                    - install