version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  unit_test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
        steps:
          - run: yarn install
      - run: yarn unit .
  build_docker:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run:
                name: Install Docker Compose
                command: |
                  set -x
                  sudo curl -L https://github.com/docker/compose/releases/download/1.25.4/run.sh -o /usr/local/bin/docker-compose
                  sudo chmod +x /usr/local/bin/docker-compose
      - setup_remote_docker:
        steps:
          - run: docker-compose up -d
workflows:
    deploy:
      jobs:
        - unit_test
        - build_docker