version: 2.1
jobs:
  # unit_test:
  #   docker:
  #     - image: circleci/node:10.16.3
  #   steps:
  #     - checkout
  #     - node/with-cache:
  #       - run: yarn install
  #     - run: yarn unit
  build_docker:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: yarn install
      - save_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
        paths:
          - ./node_modules
      - run:
          name: Install Docker Compose
          command: |
            set -x
            sudo curl -L https://github.com/docker/compose/releases/download/1.25.4/run.sh -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      # - setup_remote_docker:
      # - run:
      #       name: Start container
      #       command: |
      #         set -x
      #         docker-compose up -d
workflows:
    deploy:
      jobs:
        # - unit_test
        - build_docker